services:
    newscoop_send_feedback.lifecyclesubscriber:
        class: Newscoop\SendFeedbackBundle\EventListener\LifecycleSubscriber
        arguments:  ["@service_container"]
        tags:
            - { name: kernel.event_subscriber}

    newscoop_send_feedback.configure_menu_listener:
        class: Newscoop\SendFeedbackBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments: 
            - @translator